site_name: AutoBoat Documentation
site_url: https://localhost:8000
repo_url: https://github.com/autoboat-vt
repo_name: GitHub Organization
theme:
  name: material
  logo: images/logo.svg
  favicon: images/logo.svg
  palette:
    scheme: slate
  features:
    - content.code.copy
    - content.code.select
# theme:
#   name: readthedocs

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.arithmatex:
      generic: true
  # If you want to re-enable highlighting and TOC:
  # - pymdownx.highlight:
  #     anchor_linenums: true
  #     line_spans: __span
  #     pygments_lang_class: true
  # - toc:
  #     toc_depth: "1-1"

extra_javascript:
  - javascript/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - styles/extra.css

nav:
  - Home: index.md

  - Getting Started:
      - Installing Docker: getting_started/installing_docker.md
      - Setting Up the Development Container: getting_started/setting_up_dev_environment.md
    #   - What Did You Just Install?: getting_started/what_did_you_just_install.md
      - Installing MicroROS: getting_started/installing_microros.md
      - How to Start Developing on the Website: getting_started/how_to_develop_website.md
      - Installing and Running Deepstream for Object Detection: getting_started/install_object_detection.md

  - Examples:
      - Running the Simulation: examples/running_simulation.md
      - Connecting A USB Device to WSL: examples/connecting_a_usb_device_to_wsl.md
      - Adding Documentation: examples/adding_documentation.md
      - Adding A New External Pip Libraries that We Can Edit: examples/how_we_handle_external_libraries.md
      - Running Individual Nodes for Testing: examples/running_individual_nodes.md
      - Adding a New ROS2 Node to A Package: examples/adding_a_new_ros2_node.md
      - Adding A New ROS2 Package to the Workspace: examples/adding_a_new_ros2_package.md

  - System Diagrams:
      - Communication Between Groundstation and Autopilot: system_diagrams/diagram_of_groundstation_telemetry.md
      - How the Simulation Works and Communicates with ROS: system_diagrams/diagram_of_simulations.md
      - ROS2 Node Diagrams: system_diagrams/diagram_of_ros_nodes.md

  - Groundstation/Telemetry:
      - New Member Overview: groundstation_telemetry/new_member_info.md
      - Groundstation: groundstation_telemetry/groundstation_overview.md
      - Telemetry Server: groundstation_telemetry/telemetry_server_api_routes.md

  - ROS2 Packages and Nodes:
      - Autopilot Package:
          - Common Documentation Between the Motorboat Autopilot and the Sailboat Autopilot: ros2_packages/autopilot_package/common_documentation_between_the_motorboat_autopilot_and_the_sailboat_autopilot.md
          - Sailboat Autopilot Node: ros2_packages/autopilot_package/sailboat_autopilot.md
          - Motorboat Autopilot Node: ros2_packages/autopilot_package/motorboat_autopilot.md
          - Telemetry: ros2_packages/autopilot_package/telemetry.md

      - Sensors Package:
          - GPS Node: ros2_packages/sensors_package/gps.md
          - RC (Remote Controller) Node: ros2_packages/sensors_package/rc.md
          - Wind Sensor Node: ros2_packages/sensors_package/wind_sensor.md

      - VESC Package:
          - VESC Node: ros2_packages/vesc_package/vesc.md

      - Microros Package:
          - Raspberry Pi Pico Microros Node: ros2_packages/microros_package/microros.md

      - Object Detection Package:
          - Object Detection Node: ros2_packages/object_detection_package/object_detection.md

      - AutoBoat Messages Package:
          - AutoBoat Messages Node: ros2_packages/autoboat_messages_package/autoboat_msgs.md

      - Simulation Package:
          - Sailboat Simulation Node: ros2_packages/simulation_package/sailboat_simulation.md
    
      - New Simulation Package:
          - Motorboat Simulation: ros2_packages/new_simulation_package/motorboat_simulation.md

      - What About the Other Nodes: ros2_packages/other_nodes/what_about_the_other_nodes.md



  - Hardware:
      - Wiring Color Scheme: hardware/wiring_color_scheme.md
      - Squircuit: hardware/squircuit.md


  
  - Funding/ Business:
      - SEC Funding: finances/SEC.md
      
  - Misc:
      - Potential Security Risks: misc/potential_security_risks.md
      - Units, Standards, and Definitions: misc/standards_and_definitions.md
      - Running ROS2 on Jetson Startup with Systemctl: misc/systemctl.md
      - Automatically Finding Which Port Devices Are on with Udev Rules: misc/udev_rules.md
      - Automating Periodic Scripts with Crontabs: misc/crontabs.md
      - Known Issues: misc/known_installation_issues.md
